# Generated by Django 2.2.17 on 2021-01-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_data',
            new_name='ordered_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='start_data',
            new_name='start_date',
        ),
    ]
